/// Build metadata generated by scripts/generate_build_info.sh.
/// Do not edit manually — regenerate with: bash scripts/generate_build_info.sh
///
/// In CI/CD this file is regenerated before every build.
/// In local development run the script once after cloning.
class BuildInfo {
  BuildInfo._();

  /// Semantic version from pubspec.yaml (e.g. "1.0.0").
  static const String version = '1.0.0';

  /// Git commit count used as build number (e.g. "26").
  static const String buildNumber = '26';

  /// Short Git commit hash (e.g. "f3c3fd3").
  static const String gitCommit = 'f3c3fd3';

  /// Full Git commit hash.
  static const String gitCommitFull = 'f3c3fd3';

  /// Flutter SDK version at build time (e.g. "3.29.0").
  static const String flutterVersion = 'unknown';

  /// Dart SDK version at build time (e.g. "3.7.0").
  static const String dartVersion = 'unknown';

  /// ISO-8601 timestamp of the build.
  static const String buildDate = '2026-04-07T00:00:00Z';

  /// True when compiled in debug mode.
  static const bool isDebug = bool.fromEnvironment('dart.vm.product') == false;
}
